import type { Metadata } from "next";
import { Geist, Geist_Mono, Arimo } from "next/font/google";
import "./globals.css";
import Nav from '../components/nav'

const arimo = Arimo({
  subsets : ["latin"]
})

export const metadata: Metadata = {
  title: "Football Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.className} antialiased`}
      >
        <h1 className="text-[4em] my-5 tracking-wide">Football Stats Live</h1>
        {children}
      </body>
    </html>
  );
}
