import type { Metadata } from "next";
import { Geist, Geist_Mono, Arimo } from "next/font/google";
import "./globals.css";
import Nav from '../components/nav'

const arimo = Arimo({
  subsets : ["latin"]
})

export const metadata: Metadata = {
  title: "Football Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.className} antialiased`}
      >
        <h1 className="text-[3em] py-3 shadow-lg rounded-xl mt-5 tracking-wider font-semibold dashboard-card w-5/6 text-center main-title">Football Stats Live</h1>
        {children}
      </body>
    </html>
  );
}
